apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lms-laravel
  name: lms-laravel
  namespace: lms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-laravel
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lms-laravel
    spec:
      initContainers:
        - args:
            - /bin/bash
            - -c
            - (php artisan migrate --seed || true)
          env:
           - name: DB_CONNECTION
             value: "mysql"
           - name: DB_HOST
             value: "mysql"
           - name: DB_PORT
             value: "3306"
           - name: DB_DATABASE
             value: "lms_laravel"
           - name: DB_USERNAME
             value: "lms_user"
           - name: DB_PASSWORD
             value: "lms_password"
          image: php
          imagePullPolicy: Always
          name: artisan
      containers:
      - image: 481258723266.dkr.ecr.us-east-1.amazonaws.com/laravel-lms:7
        name: laravel-lms
        resources: {}